HOST: https://uat.payleap.com/TransactServices.svc
--- TransactServices ---
POST /ProcessCreditCard
> Content-Type: application/json
{ "UserName":"API UserName", "Password":"TransactionKey", "TransType":"Sale", "NameOnCard":"John Doe","CardNum":"4111111111111111", "ExpDate":"1215", "CVNum":"123", "Street":"123 street", "City":"Seattle", "State":"WA", "Zip":"98498", "InvNum":"abc123", "PNRef":"", "MagData":"", "ExtData":"": }
< 201
< Content-Type: application/json
{ "status": "created", "url": "/shopping-cart/2" }