--- TransactServices ---
POST http://private-b1d2-transactservices1.apiary.io
> Content-Type: text/xml
{ "UserName":"API UserName", "Password":"TransactionKey", "TransType":"Sale", "NameOnCard":"John Doe","CardNum":"4111111111111111", "ExpDate":"1215", "CVNum":"123", "Street":"123 street", "City":"Seattle", "State":"WA", "Zip":"98498", "InvNum":"abc123", "PNRef":"", "MagData":"", "ExtData":"": }
< 201